version: "3.7"

services: 
  database:
    image: mysql
    container_name: processo_seletivo_database
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: dictionary_database
      MYSQL_USER: mysql
      MYSQL_ROOT_PASSWORD: mysqlrpw
      MYSQL_PASSWORD: mysqlpw
    # volumes:
    #   - pgdata:/data/postgres
  app:
    build: .
    container_name: processo_seletivo_api
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
volumes:
  pgdata:
    driver: local